import Head from "next/head";

import Layout from "@components/Layout";
import Header from "@components/Header";
import Container from "@components/Container";
import Button from "@components/Button";

import styles from "@styles/Product.module.scss";
import { ApolloClient, InMemoryCache, gql } from "@apollo/client";

export default function Product(product) {
  console.log(product.product.name);
  const { name, price, description } = product.product;

  return (
    <Layout>
      <Head>
        <title>{product.name}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <div className={styles.productWrapper}>
          <div className={styles.productImage}>img</div>
          <div className={styles.productContent}>
            <h1>{name}</h1>
            <div className={styles.productDescription}>
              <p>{price}</p>
            </div>
            <p className={styles.productPrice}>${price}</p>
            <p className={styles.productBuy}>
              <Button>Add to Cart</Button>
            </p>
          </div>
        </div>
      </Container>
    </Layout>
  );
}
export async function getStaticProps({ params }) {
  const client = new ApolloClient({
    uri:
      "https://api-us-east-1.graphcms.com/v2/cl4o3gra10bbs01xr46y1b6i6/master",
    cache: new InMemoryCache(),
  });
  const data = await client.query({
    query: gql`
      query PageProduct($slug: String) {
        product(where: { slug: $slug }) {
          name
          price
          slug

          description {
            html
          }
        }
      }
    `,
    variables: {
      slug: params.productSlug,
    },
  });
  console.log(data);
  const product = data.data.product;
  return {
    props: {
      product,
    },
  };
}
export async function getStaticPaths() {
  const client = new ApolloClient({
    uri:
      "https://api-us-east-1.graphcms.com/v2/cl4o3gra10bbs01xr46y1b6i6/master",
    cache: new InMemoryCache(),
  });
  const data = await client.query({
    query: gql`
      query PageProducts {
        products {
          name
          price
          slug

          description {
            html
          }
        }
      }
    `,
  });
  const paths = data.data.products.map((product) => {
    return {
      params: {
        productSlug: product.slug,
      },
    };
  });
  return {
    paths,
    fallback: false,
  };
}
